# Generated by Django 5.0.1 on 2024-02-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="products",
            field=models.ManyToManyField(to="shop.product"),
        ),
    ]
