# Generated by Django 5.0.1 on 2024-02-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
